# ============================================================
# Filgo-Sonic — Configuration environnement
# ============================================================
# Environnement actif : DEV | QA | PROD
lcr_environment=DEV

# ============================================================
# DEV
# ============================================================
lcr_dataverse_url_dev=https://dev-filgo-sonic.crm3.dynamics.com
lcr_dataverse_scope_dev=https://dev-filgo-sonic.crm3.dynamics.com/.default
lcr_fs_app_id_dev=91a8643f-21db-ee11-904c-002248b1ce29
lcr_azure_client_id_dev=ec9ea9bc-e972-4407-962b-b17ccd050380

# ============================================================
# QA — à compléter
# ============================================================
lcr_dataverse_url_qa=
lcr_dataverse_scope_qa=
lcr_fs_app_id_qa=
lcr_azure_client_id_qa=

# ============================================================
# PROD — à compléter
# ============================================================
lcr_dataverse_url_prod=
lcr_dataverse_scope_prod=
lcr_fs_app_id_prod=
lcr_azure_client_id_prod=