
// settings.gradle (remplacer tout le contenu par ceci)

pluginManagement {
  repositories {
    gradlePluginPortal()
    google()
    mavenCentral()
  }
  plugins {
    id 'com.android.application' version '8.5.2'
  }
}

dependencyResolutionManagement {
  repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
  repositories {
    google()
    mavenCentral()

    // ➜ Dépôt JitPack requis pour usb-serial-for-android (mik3y)
    //   (la lib n'est pas sur mavenCentral()/google())
    maven { url "https://jitpack.io" }
  }
}

rootProject.name = 'lcr_android_harness_v2'
include(':app')
