pluginManagement {
  repositories {
    gradlePluginPortal()
    google()
    mavenCentral()
  }
  plugins {
    id 'com.android.application' version '8.5.2'
  }
}

dependencyResolutionManagement {
  repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
  repositories {
    google()
    mavenCentral()
    // JitPack pour usb-serial-for-android
    maven { url "https://jitpack.io" }
    // ✅ Microsoft — requis pour MSAL (display-mask + identity libs)
    maven { url "https://pkgs.dev.azure.com/MicrosoftDeviceSDK/DuoSDK-Public/_packaging/Duo-SDK-Feed/maven/v1" }
  }
}

rootProject.name = 'lcr_android_harness_v2'
include(':app')
